### ISSUE TITLE
On the suggested lexical syntax of identifiers

### ISSUE THREAD

**Issue by marcomaggi** [oden-lang/oden#28]
It seems you want to suggest CamelCase convention for identifiers.  This is not very lispy; under Lisp `this-is-the-preferred-convention` and there are many editors that expect it.  It fits.

**Comment by owickstrom** [comment]
No, not really. The identifiers imported from Go will have their casing preserved, so they will have CamelCase names for exported names. Code written in Oden should be `written-like-this`. I think this is comparable to how interfacing with Java works in Clojure.

During Oden compilation symbols get translated to camelCase because Go does not support dashes in identifiers. The translated names should be UpperCamelCase but I haven't gotten around to fix that. When introducing some kind of public/private notion in Oden the identifiers need to be translated to UpperCamelCase and lowerCamelCase, respectively.

Does this sound reasonable?

**Comment by marcomaggi** [comment]
> Code written in Oden should be `written-like-this`.

Good.

> Does this sound reasonable?

Yes, and I understand the pressure from the Go side to have compatible identifiers.  In general, once you embrace Lispy syntax, there are some things lispers expect; so `1+` is expected to be a valid identifier by many.  Some dialects of Lisp are very liberal in what is considered a valid identifier, for example `number->string`, `->string`, `=>` are all valid identifiers.  It is troublesome to convert those into human-readable Go identifiers, maybe you should make the constraint on readable Go "optional" and go with generated unique identifiers (like `g123`).

**Comment by owickstrom** [comment]
Yeah, I've come to know some of the expectations that people have on a language that has a Lispy syntax. :smile: However, Oden is not intended to be a dialect of any existing Lisp. I want to keep these conversations open-minded, not getting stuck at how it's done in CL or Scheme. Then again, like you mentioned, staying close to the existing Lisps gives Oden the benefit of being able to leverage existing editor and tooling support. Therefore, giving the exact same freedom in naming as in other Lisps do is not a strict goal, but absolutely something to strive for.

On the subject of readable Go code [this is listed in the *Goals* section](http://oden-lang.org/motivation-and-goals.html#shortcutstradeoffs) as something not to focus on, so ugly Go code is totally fine. The symbol `=>` gets converted to `_EQ__GT_` in the Go output.

**Comment by marcomaggi** [comment]
> Yeah, I've come to know some of the expectations that people have on a language that has a Lispy syntax.

I totally understand you.  On this subject I just want to report that it is possible to devise a lispy syntax such that: once the lexer knows the first 1 or 2 characters of the next token, it knows the category of the lexeme.  This may speed up lexing.

**Comment by owickstrom** [comment]
Cool. The current lexer is super-simple but this kind of customization may very well be necessary in the future.
