### ISSUE TITLE
Wrapping go tuples (multiple return values) into Oden tuples on import

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#56]
The Go FFI module needs to automatically convert multiple return values into a single tuple return value for interoperability.

**Comment by patchypatchypatchy** [comment]
just an observation about tuples and go's "tuples"

the proper middle ground i believe would be to make all tuple types a function which takes no parameters and returns multiple values.

this would behave exactly like a tuple ( immutable, arbitrary typing per value, already interoperable with go) and it would make some other potential difficulties in implementing tuples as a struct totally go away.

these include needing to worry about tuples being mutated, managing go functions which are intended to accept "tuples" (which will likely create some boilerplate being generated unless your careful). of course if someone uses reflect or something similar to modify a struct based tuple, it will likely be on purpose, though that may not be a good enough reason to prevent it.

the standard example in go of using "tuples" as both a function 'input' and 'output' being something along the lines of:

func a([]byte x,err y) string, err
func b (string x) []byte, err

s,e := a(b("foo"));

there is likely a lot of room for error in generating boilerplate between go "tuples" and open tuples should they remain a struct due to examples like that, especially if i want to put oden function c between a and b.

that said being able to use all of the go functions with multiple return values in open properly will be amazing and i look forward to the day that comes.

**Comment by owickstrom** [comment]
This is a very interesting idea. I'm currently processing it, trying to think this through. Just so I understand you correctly - a tuple literal `(1, "x", 1)` will be captured in a closure:
```go
// (1, "x", 1) in Oden
func () (int, string, int) { return 1, "x", 1 }
````

That func value will be passed around, typed as `(int, string, int)` in Oden, until the values needs to be extracted, e.g. in an destructuring assignment:

```go
// let (x, y, z) = (1, "x", 1)
var x int
var y string
var z int
x, y, z = (func () (int, string, int) { return 1, "x", 1 })()
```

The biggest benefit I can see with this is that we can leverage the multiple return value and assignment construct in Go. If we implement tuples as structs we need to do some clever name generating for the intermediate struct:

```go
// let (x, y, z) = (1, "x", 1)
generated_unique_intermediate_name := struct {
	_0 int
	_1 string
	_2 int
}{1, "x", 1}

var x int = generated_unique_intermediate_name._0
var y string = generated_unique_intermediate_name._1
var z int = generated_unique_intermediate_name._2
```

> there is likely a lot of room for error in generating boilerplate between go "tuples" and open tuples should they remain a struct due to examples like that, especially if i want to put oden function c between a and b.

I'm not sure the automatic usage of multiple return values as function arguments is something we want. As we transform the tuple type to a first class type, just like any other value type, I think it makes sense to remove that sort of "magic". Instead we could use a "spread operator" `...` for applying functions with tuples, like applying functions with slices in Go.

> of course if someone uses reflect or something similar to modify a struct based tuple, it will likely be on purpose, though that may not be a good enough reason to prevent it.

This is absolutely possible in theory, but I don't think we should worry about it.

**Equality**:

One thing we loose by using functions is value equality. The struct approach gives us equality with `==` "for free".

**Performance**:

There's also the performance aspect. Please correct me if I'm wrong, but the func value is a reference type where the struct is a value type on the stack. A quick benchmark points to structs being ~6x faster:

```go
package main

import "testing"

func receiveStructTuple(a struct {
	_0 int
	_1 string
	_2 int
}) {
	_ = a._0 * a._2
}

func createStructTuple() struct {
	_0 int
	_1 string
	_2 int
} {
	return struct {
		_0 int
		_1 string
		_2 int
	}{1, "x", 1}
}

func createFuncTuple() func() (int, string, int) {
	return func() (int, string, int) {
		return 1, "x", 1
	}
}

func receiveFuncTuple(a func() (int, string, int)) {
	x, _, y := a()
	_ = x * y
}

func BenchmarkStructTuple(b *testing.B) {
	for i := 0; i < b.N; i++ {
		receiveStructTuple(createStructTuple())
	}
}
func BenchmarkFuncTuple(b *testing.B) {
	for i := 0; i < b.N; i++ {
		receiveFuncTuple(createFuncTuple())
	}
}
```

```
$ go test -bench=.
testing: warning: no tests to run
PASS
BenchmarkStructTuple-8  2000000000               0.86 ns/op
BenchmarkFuncTuple-8    300000000                5.11 ns/op
```

**Other?**

Is there anything else to consider here?

**Comment by AlbinTheander** [comment]
Short thread with long posts. :-)

I like the immutability factor with the functions and the fact that we don't have two Oden types that match to the same Go type (structs and tuples in Oden both maps to structs in Go).

The ability to pass a multi-value function directly as a parameter to a multi-argument function is nice, but is more of a Go thing. All Oden functions are curried, so strictly speaking they only take one argument. Spreading a multi-value over them would involve some kind of uncurrying.

> If we implement tuples as structs we need to do some clever name generating for the intermediate struct:

I'm not sure that's necessary. We can probably use an intermediate, anonymous function to unpack the "tuple-structs" into singular values:

```Go
// let (x, y, z) = (1, "x", 1)
var x int
var y string
var z int
x,y,z = func (in struct {_0 : int; _1 string; _2; int}) (int, string, int) {
   return in._0, in._1, in._2
} (struct{_0: int; _1 string; _2; int}{1, "x", 1})
```

It isn't the prettiest code ever, but it's easy to generate and it avoids any name conflicts.

**Comment by AlbinTheander** [comment]
I use the wrapping strategy mentioned above in my pull request #62, but in the reverse way to pack multiple return values into a struct. The details are in the pull request details.

**Comment by patchypatchypatchy** [comment]
i was thinking about this further today and came to 2 realizations.

1. the speed loss for backing tuples as functions would be minor compared to the gratuitous amounts of curring that happens elsewhere in oden code (currently at least?).

and more importantly:
2. if the potential for users working around the immutable-ness of tuples isnt noteworthy, then storing variables in a function to enforce immutability is not really needed anymore - you can store a tuple as a series of instance variables. that would mean that a tuple would (unfortunately) need an interesting name generation scheme in the conversion step from oden to go, but aside from that i dont see any downsides from this approach.

this could reduce gratuitous currying (currently by design) by making functions designed to take multiple params just require tuples as input (reserving curring for cases where things are improved by the practice, if coders so desire), greatly simplify the idea of unpacking tuples from go functions, calling go functions with a tuple param, and finally keep the concept of a go "tuple" pure between both lanuage specs (well pure as far as go is concerned).

the name generation step i did gloss over may actually be a bit of a problem though, unless there are rules about what an oden variable name can look like (ie unable to start with an underscore). failing that you would need to dynamically generate a variable name that would otherwise not be defined in the oden function where the tuple is named, and im not sure i understand the added complexity related to doing that.

thought id share this idea since it just hit me today.

**Comment by owickstrom** [comment]
Closed by https://github.com/oden-lang/oden/pull/62
