### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#7]
This is a big one...

**Comment by vishesh** [comment]
+1 for hygienic macros! (makes it bigger). I don't know how macros are implemented, but perhaps it can be done on top of naive macro expander.

**Comment by owickstrom** [comment]
Not sure if you mean how macros are implemented in general, but there's nothing implemented in Oden right now anyway. This needs some serious up-front work and may not get done any time soon, but I'd like for the discussion to get going here right from the start.

**Comment by vishesh** [comment]
Yeah, macros would require serious work. What I meant was, sometime in future it would be good to have hygienic macros. Would be very ambitious, but if they can be built over naive expander itself we probably don't have to worry about them at all for now and just focus on naive expander.

**Comment by owickstrom** [comment]
I'm not sure I follow on the "naive expander" part, maybe a term I'm not familiar with. :smiley:  Do you have some references to link to or care to explain?

**Comment by vishesh** [comment]
If expander doesn't care about hygiene its is naive. I picked it from here[1]. Its pretty old so perhaps its not standard term. Hygienic macros are those which makes sure that you don't accidentally shadow identifiers. Hope this makes my point clear -

    (define-syntax my-or
      (syntax-rules ()
        [(_ exp1 exp2)
         (let ([tmp exp1])
           (if tmp exp1 exp2))]))

    (let ([tmp 4])
      (my-or #f tmp))

    ;; with naive macro expansion
    ;; above expression would simply expand to
    (let ([tmp 4])
      (let ([tmp #f])
        (if tmp #f tmp)))

[1] http://web.cs.ucdavis.edu/~devanbu/teaching/260/kohlbecker.pdf

**Comment by owickstrom** [comment]
Absolutely, I just needed the term clarified. :) Thanks!

**Comment by marcomaggi** [comment]
I cannot shut up about hygienic macro expansion... it is a **very hard** subject...

> [1] http://web.cs.ucdavis.edu/~devanbu/teaching/260/kohlbecker.pdf

The algorithm described in this paper is known as KFFD (from the initials of the authors); AFAIK it is the very first algorithm that introduced hygienic macro expansion.  This algorithm is considered *obsolete* because it is very slow and it does not scale well with the size of the input code.  There is a better algorithm described (among others) in chapter 2 of:
```
Oscar Waddell.  ``Extending the Scope of Syntactic Abstraction''.
Ph.D. thesis.  Department of Computer Science, Indiana University.
August 1999.
```
and also this short introduction:
```
R.  Kent Dybvig.  ``Writing Hygienic Macros in Scheme with Syntax-Case''.
Department of Computer Science, Indiana University.
Technical Report 356.  June 1992.
```
and also this:
```
Abdulaziz Ghuloum.  ``Implicit Phasing for Library Dependencies''.  Ph.D. thesis.
Department of Computer Science, Indiana University.  December 2008.
```

This algorithm has variations (*implicit phasing*, *explicit phasing*, various degrees of *phase separation*) but in the end it is all about renaming syntactic bindings.  Another approach, introduced recently in Racket, is [Binding as Sets of Scopes](https://www.cs.utah.edu/plt/scope-sets/); I have not studied it, so I cannot say much about it (but its authors are very very expert in this subject).

So, what about renaming syntactic bindings?  Let's step back a moment.

When talking about hygienic macro expansion (HME), we are talking about applying to the source code a preprocessor pass in which the macros are implemented using the full power of the language itself;  in the context of HME the preprocessor is called *expander*.  The m4 preprocessor applied to a C language source has macros written in the m4 language, while an oden hygienic macro expander would have  macros written in oden itself.  Unfortunately, past experience with preprocessors will help very little when using and implementing an expander (this is my experience).

The expander transforms input source code into output source code; the expander can be seen as a single (very complex) pass into a [multi-pass compiler](http://www.cs.indiana.edu/~dyb/pubs/nano-jfp.pdf).  When the input source code defines no macros: still the expander transforms the input into a different output; it is of paramount importance to understand this "no-macro" transformation if we want to understand HME.

Let's take this simple input source code:
```
(let ((x 1))
  (list x x))
```
the binding syntax `let` *establishes* the syntactic binding `x` (it is a *variable* syntactic binding); the syntactic identifier `x` appears first in *binding* position in the form `(x 1)`, then twice in *reference* position in the form `(list x x)`.  We want the syntactic identifiers `x` in reference position to be *captured* by the syntactic binding established by `let`.

The expander visits this input code with a recursive iteration that can be seen as a preorder tree iteration; the iterator accepts as input values named *syntax objects* representing the input code and outputs fully expanded code.  The first syntax object holds the full input code:
```
(let ((x 1)) (list x x))
```
then the iterator is applied to these nested syntax objects:
```
let
((x 1))
(x 1)
x
1
(list x x)
list
x
x
```
the expander recognises `let` as a language built-in syntax and `list` as a language built-in primitive.

We can imagine the result of the full expansion as the following symbolic expression:
```
(let ((lex.x 1))
  ((primitive list) lex.x lex.x))
```
notice how `list` is marked as primitive and the syntactic identifiers `x` have been **renamed** to `lex.x` which we can call the *lexical name* of `x`.

Let's take this input code:
```
(let ((x 1))
  (let ((x 2))
    (list x x)))
```
it should be expanded to:
```
(let ((lex.x.1 1))
  (let ((lex.x.2 2))
    ((primitive list) lex.x.2 lex.x.2)))
```
the syntactic identifiers `x` in reference position are correctly captured by the internal syntactic bindings, so they are renamed to `lex.x.2`.

Now let's open a paranthesis.  With the C language preprocessor we can write:
```
#define doit(x,y)            list(x,y)
```
so that the *macro use* `doit(1,2)` is replaced with `list(1,2)`.  Under a non-standard Scheme dialect this simple macro can be written as follows:
```
(define-syntax-rule (doit ?x ?y)
  (list ?x ?y))
```
so that the *macro use* `(doit 1 2)` is first replaced with `(list 1 2)` and finally expanded to `((primitive list) 1 2)`.  The *pattern* `(doit ?x ?y)` matches the macro use `(doit 1 2)`; the macro use syntax object is decomposed and an output syntax object is built as `(list 1 2)` which then is recursively expanded.

Let's consider this input code:
```
(let ((x 1))
  (define-syntax-rule (doit)
    x)
  (let ((x 2))
    (list (doit) x)))
```
it will be expanded to:
```
(let ((lex.x.1 1))
  (let ((lex.x.2 2))
    ((primitive list) lex.x.1 lex.x.2)))
```
notice how we are able to introduce in the internal form `(list (doit) x)` a reference to the outer syntactic binding for `x`.  This is possible because we are renaming syntactic bindings.

How `define-syntax` works is a bit advanced when doing a first overview, but I will add a note anyway.  The general use of the syntax `define-syntax` is:
```
(define-syntax ?lhs ?rhs)
```
were the left-hand side `?lhs` must be a syntactic identifier and the right-hand side `?rhs` must be an expression.  `?rhs` must evaluate, at *expand-time*, to a function called *macro transformer*.  The transformer must accept as single argument the *input form*: a syntax object representing a macro use.  The transformer must return as single value the *output form*: a syntax object representing the output of the macro use; the output form will be recursively expanded.

The definition of a macro that does nothing by returning as output form the very syntax object representing the input form is:
```
(define-syntax doit (lambda (stx) stx))
```
the macro use `(doit)` will be transformed into itself, resulting in infinite recursion in the expander.  A macro definition that always expands into the number `1` is:
```
(define-syntax doit (lambda (stx) 1)
```
the number `1` is a valid syntax object; the macro use `(doit)` just expands into `1`.

An expander must implement an API to unpack the syntax object representing the input form and pack a syntax object representing the output form, this is usually done with some form of pattern matching.  This is where the power of macros shows: a macro transformer is a function written in the language itself, so it can do everything that the language itself allows.

I hope this short introduction to the basic concepts is helpful in finding your way through the vast literature about HME.  If you want to implement an expander, you can have a good start by structuring the compiler as multi-pass; then implementing the first pass as a "syntax objects representation" to "lexical internal representation" transformation.

**Comment by owickstrom** [comment]
Closing this and moving high-level discussions to https://groups.google.com/forum/#!forum/oden-lang.
