### ISSUE TITLE
Why forall?

### ISSUE THREAD

**Issue by alexanderzafirov** [oden-lang/oden#98]
Hello, first off - I like the idea for Oden very much! I hope the project does great :)
Can you please explain to me why you have the `forall` construct? In Haskell you don't need a special keyword for type variables. In my mind this just clutters the code. 
Maybe I am not seeing some dependency that Go enforces or I haven't read the docs properly?

**Comment by owickstrom** [comment]
Hi! Thank you, nice to hear! :)

Sure, it's because type variables and type constructors in Haskell has separate namespaces - in Oden they do not. I wrote a more elaborate answer here: https://github.com/oden-lang/oden/issues/55#issuecomment-193621461.

This is least the current state of Oden, it might change in the future. I like having explicitness as a default, so until things are fully decided on this front we'll have to write `forall`. :)

I hope that answers your question well!

**Comment by alexanderzafirov** [comment]
Yes, it does. Thank you for the quick reply!

**Comment by owickstrom** [comment]
No problem, I'm happy to answer your questions!
